package:
  name: arrow
  version: "0.10.0"

source:
  fn: arrow-0.10.0.tar.gz
  url: https://pypi.python.org/packages/54/db/76459c4dd3561bbe682619a5c576ff30c42e37c2e01900ed30a501957150/arrow-0.10.0.tar.gz
  md5: 5d00592200050ad58284d45a4ee147c6
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - arrow = arrow:main
    #
    # Would create an entry point called arrow that calls arrow.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-dateutil

  run:
    - python
    - python-dateutil

test:
  # Python imports
  imports:
    - arrow

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/crsmithdev/arrow/
  license: Apache Software License
  summary: 'Better dates and times for Python'
  license_family: APACHE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
