package:
  name: pdfminer.six
  version: "20170419"

source:
  fn: pdfminer.six-20170419.tar.gz
  url: https://pypi.python.org/packages/43/71/b592b9b384c9bc4429e9a35cc9d61a5eb7fabef2208140c30550a474defe/pdfminer.six-20170419.tar.gz
  md5: c43b443ad759441adb07fde5f1ca3435
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pdfminer.six = pdfminer.six:main
    #
    # Would create an entry point called pdfminer.six that calls pdfminer.six.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six
    - pycrypto
    - chardet

  run:
    - python
    - six
    - pycrypto
    - chardet

test:
  # Python imports
  imports:
    - pdfminer

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/pdfminer/pdfminer
  license: MIT License
  summary: 'PDF parser and analyzer'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
