package:
  name: nbsphinx
  version: "0.2.13"

source:
  fn: nbsphinx-0.2.13.tar.gz
  url: https://pypi.python.org/packages/ec/89/0e170282547362e4cd3648a85fb326ae0e8bcbaea54241c73bda6ac36bfb/nbsphinx-0.2.13.tar.gz
  md5: 4816354e6820c009e4c9d2bba6cf830c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nbsphinx = nbsphinx:main
    #
    # Would create an entry point called nbsphinx that calls nbsphinx.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - docutils
    - jinja2
    - nbconvert
    - traitlets
    - nbformat
    - sphinx >=1.3.2,!=1.5.0

  run:
    - python
    - docutils
    - jinja2
    - nbconvert
    - traitlets
    - nbformat
    - sphinx >=1.3.2,!=1.5.0

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://nbsphinx.rtfd.io/
  license: MIT License
  summary: 'Jupyter Notebook Tools for Sphinx'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
